### ISSUE TITLE
Tests multiple contracts in one package in rust runner

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1847]
Currently users need to create separeate package for each contract. It should be possible to define multiple contracts inside single package

**Comment by cptartur** [comment]
What I found out: 

Adding support for building multiple contracts in package seems easy enough - cairo1 repo already has some kind of support for it, and we can just modify their code (should work even on alpha.6 compiler version). 

However, we're defining contracts in `protostar.toml` where we are using a path to the whole package as a path to contract. This is because contracts have to be compiled in the context of the whole package.

For multiple contracts per package to work, we'd have to use some different definition mechanism, so we're able to distinguish between contracts in package while still being able to compile them.

Some ideas for that:

- use some different mapping in `protostar.toml` like `contract_name -> (package, contract_path/name)`
- map `contract_name -> (path_to_contract)` and traverse the directory upwards searching for containing package
- some other combination of this mapings
- require manual building and go back to using paths to compiled jsons (this is problematic because paths likely won't fit in cheatcodes, just json names could be used instead but it's still problematic)

These are just ideas, there might exist a better solution for that.

**Comment by cptartur** [comment]
Blocked until #2059 is merged

**Comment by cptartur** [comment]
Blocked by fork sync

**Comment by cptartur** [comment]
Cairo 1 fork requires update to change build artifacts finding logic. It's not using `starknet_artifacts.json` at all, and matching by the first part of the name (package) instead of contract name.
