### ISSUE TITLE
Verify if defining tests with imports within a package works for python runner

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1973]

**Comment by piotmag769** [comment]
It works for me.
[cairo1.zip](https://github.com/software-mansion/protostar/files/11555874/cairo1.zip)

**Comment by piotmag769** [comment]
TL;DR: use absolute paths.

The problem was passing relative paths as linked-libraries to the compiler. It got fixed by accident with Scarb integration PR because `scarb metadata` returns absolute paths.

I have no idea what exactly the compiler does under the hood that makes this particular case break, but others not.

cc @karol-bisztyga @cptartur @MaksymilianDemitraszek
