### ISSUE TITLE
Compilation of contract to sierra failed even though scarb build runs fine

### ISSUE THREAD

**Issue by tensojka** [software-mansion/protostar#2049]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.13.0`  |
| Cairo-lang | `0.11.1.1` |
| Cairo 1 compiler version | `1.1.0` |
| Scarb | `0.4.0` |

## Current Behavior
![Snímek obrazovky 2023-06-07 v 15 23 48](https://github.com/software-mansion/protostar/assets/8470346/a6a8a7ef-aee2-4a1e-9e0d-ba7f8cdd4bd5)

## Expected Behavior
The tests aren't broken and either fail or succeed.

## Steps to Reproduce
1. Clone [governance](https://github.com/CarmineOptions/governance.git)
2. git checkout add-tests
3. Run scarb build, succeeds
4. Run scarb test, fails during compilation

Specific commit ID with reproduction of the bug is b0c280c77b2827f17e8c910272768ab0bcf01e74.

**Comment by piotmag769** [comment]
@tensojka your path to contract in protostar.toml is not correct, it should look like this:
```toml
[project]
protostar-version = '0.13.0'

[contracts]
governance = ["src"]
```
https://docs.swmansion.com/protostar/docs/cairo-1/protostar-toml#contracts-section

Moreover, I see you use `cairo_project.toml` - it is not supported by Protostar anymore since it uses Scarb to manage dependencies. TLDR; use `Scarb.toml` only, you do not need `cairo_project.toml` anymore.
