### ISSUE TITLE
Change `start_prank` so that it can be used with `deploy_contract`

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#342]
## Problem
- doing `start_prank(caller_address=123, target_contract_address=None)` will only make the prank in the context of the test runner contract, not the contract actually being tested
- doing `start_prank(caller_address=123, target_contract_address=ids.deployed_contract)` wouldn't really work as we would need the contract address in advance

## Possible solutions
- `start_prank` should affect all contracts by default 
- `start_prank(caller_address=123, target="ANY")`

**Comment by MaksymilianDemitraszek** [comment]
`start_prank should affect all contracts by default` I we should do this, handling `ANY` is too complicated

**Comment by sambarnes** [comment]
> start_prank should affect all contracts by default

+1. this feels like a sane default to me

Also, i don't think it matters in this case, but maybe worth considering the implications on [delegate/library calls](https://www.cairo-lang.org/docs/hello_starknet/calling_contracts.html#library-calls). IIUC it doesn't matter since:

> ... `get_caller_address()` and `get_contract_address()` will return the same value they would have returned if they were called from the calling function.

Seems it should be fine, but figured I'd mention it in case I'm thinking about it wrong :)

**Comment by MaksymilianDemitraszek** [comment]
Closing, will be solved by https://github.com/software-mansion/protostar/issues/352
