### ISSUE TITLE
Detect slow tests. Remove `--report-slowest-tests` flag.

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#552]
Use percentiles/distribution.

**Comment by mkaput** [comment]
I have researched the state of the art in other test runners and I have concluded that nobody does this because not only it is not possible to "invent" a magic threshold (even in percentages), and also users need a way to get informed that in general all their tests are slow uniformly. Therefore, I think we can abandon this idea and leave this feature as-is.
