### ISSUE TITLE
Improve deployment script

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#733]
- do not push directly to master
- create tests

**Comment by mkaput** [comment]
I am thinking about this right now, and I think we can't easily prevent this script from pushing directly to master in a simple way. The culprit is that this script also has to push a tag. If we submit a PR, tag creation would have to be deferred and either this script would have to be wizard-style with human intervention, or it would have to automatically submit a PR and wait for merge in single run. Both are making UX of releases worse.

Regarding tests, currently this is so simple that I don't think we will benefit from having these?

Let's close this task then?

**Comment by kasperski95** [comment]
Hmm. Tags won't survive squashing.

Can we add tests for the deployment script?

**Comment by mkaput** [comment]
> Can we add tests for the deployment script?

We could, but given that we have recently shaved more specific features from this script and basically right now it's just a bunch of file reads/writes and commits -- the tests IMHO wouldn't really benefit us as they would just repeat the script's functionality and therefore only bring maintenance burden.
