### ISSUE TITLE
Parametrize API inconsistency

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#982]
Our default strategy for parametrized tests is fuzzing. I believe there may be a benefit in making it explicit.

Argument pro this change is it increases the discoverability of the framework.
If you always write `given`, it gives users not familiar with protostar a keyword they can look for in documentation, and read about fuzzing. Without it, they are left wondering what is happening, and where those parameters come from.
It makes an interface a little more consistent as well.

On the other hand it may sometimes create extra boilerplate.

Core question is, how often is fuzzing used without any strategy?

@mkaput @karol-bisztyga

**Comment by mkaput** [comment]
> Core question is, how often is fuzzing used without any strategy?

I don't know how much this is in Protostar, but these are well known facts:
1. We started with `given`-less API, where fuzzing kicked in if you provided arguments.
2. Foundry does not have analogous functionality to `given` nor `example`. They simply fuzz over all parameters in arbitrary way.

**Comment by karol-bisztyga** [comment]
I think we can do that, but I understand that, in such a case, if we do not use anything (neither `given` nor `example`), there's going to be no data to be tested, right? If we provide a proper message then (something like "empty data set, please use `example`, `given` or something else..."), it's going to be more logical for the users like Max said (at least I understood it that way). There's going to be just a little bit more boilerplate, but I'd lean toward this rather than something invisible to the users going on in the background which is not super user-friendly.

**Comment by mkaput** [comment]
Yeah I do agree that using parameters without telling Protostar what to do with them should lead to an error. I think this might be a good resolution of the problem.
